# Generated by pykickstart v3.66
#version=DEVEL
# Firewall configuration
firewall --enabled --service=mdns
# Keyboard layouts
keyboard 'us'
# System language
lang en_US.UTF-8
# Network information
network  --bootproto=dhcp --device=link --activate
# Shutdown after installation
shutdown
repo --name="fedora" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch
repo --name="updates" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f$releasever&arch=$basearch
# Root password
rootpw --iscrypted --lock locked
# SELinux configuration
selinux --enforcing
# System services
services --disabled="sshd" --enabled="NetworkManager,ModemManager"
# System timezone
timezone US/Eastern
# Use network installation
url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch"
# X Window System configuration information
xconfig  --startxonboot
# System bootloader configuration
bootloader --location=none
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all
# Disk partitioning information
part / --size=8576

%post
# Enable livesys services
systemctl enable livesys.service
systemctl enable livesys-late.service

# enable tmpfs for /tmp
systemctl enable tmp.mount

# make it so that we don't do writing to the overlay for things which
# are just tmpdirs/caches
# note https://bugzilla.redhat.com/show_bug.cgi?id=1135475
cat >> /etc/fstab << EOF
vartmp   /var/tmp    tmpfs   defaults   0  0
EOF

# work around for poor key import UI in PackageKit
rm -f /var/lib/rpm/__db*
echo "Packages within this LiveCD"
rpm -qa --qf '%{size}\t%{name}-%{version}-%{release}.%{arch}\n' |sort -rn
# Note that running rpm recreates the rpm db files which aren't needed or wanted
rm -f /var/lib/rpm/__db*

# go ahead and pre-make the man -k cache (#455968)
/usr/bin/mandb

# make sure there aren't core files lying around
rm -f /core*

# remove random seed, the newly installed instance should make it's own
rm -f /var/lib/systemd/random-seed

# convince readahead not to collect
# FIXME: for systemd

echo 'File created by kickstart. See systemd-update-done.service(8).' \
    | tee /etc/.updated >/var/.updated

# Drop the rescue kernel and initramfs, we don't need them on the live media itself.
# See bug 1317709
rm -f /boot/*-rescue*

# Disable network service here, as doing it in the services line
# fails due to RHBZ #1369794
systemctl disable network

# Remove machine-id on pre generated images
rm -f /etc/machine-id
touch /etc/machine-id

%end

%post

# set livesys session type
sed -i 's/^livesys_session=.*/livesys_session="gnome"/' /etc/sysconfig/livesys

%end

%packages
@^workstation-product-environment
@anaconda-tools
aajohan-comfortaa-fonts
anaconda-install-env-deps
anaconda-live
anaconda-webui
dracut-live
glibc-all-langpacks
gnome-initial-setup
kernel
kernel-modules
kernel-modules-extra
livesys-scripts
-@dial-up
-@input-methods
-@standard
-device-mapper-multipath
-fcoe-utils
-gfs2-utils
-python3-botocore
-reiserfs-utils
-sdubby
# Dev tools
git
vim-enhanced
tmux
htop
curl
wget

# Python
python3
python3-pip

# Containers
podman
buildah
# Bootloader (CRITICAL)
grub2-pc-modules
grub2-efi-x64
shim-x64
grub2-common

# === DEV TOOLS EXPANSION (v1.1) ===

# Core CLI
jq
tree
bat
ripgrep
fzf
fd-find

# Build tools
gcc
gcc-c++
make

# Dev tools
ShellCheck

# Node
nodejs
npm

# Containers / DevOps
skopeo
toolbox

# Networking
openssh-clients

%end

%post

# === GNOME DEV DEFAULTS (v1.2) ===

mkdir -p /etc/dconf/db/local.d
mkdir -p /etc/dconf/profile

# dconf profile
cat > /etc/dconf/profile/user <<EOF
user-db:user
system-db:local
EOF

# GNOME settings
cat > /etc/dconf/db/local.d/00-feddev <<EOF
[org/gnome/desktop/interface]
color-scheme='prefer-dark'
clock-show-weekday=true

[org/gnome/nautilus/preferences]
show-hidden-files=true
default-folder-viewer='list-view'

[org/gnome/desktop/peripherals/touchpad]
tap-to-click=true
EOF

# Apply settings
dconf update

%end
